---
- name: Get CUCM version
  hosts: localhost
  gather_facts: false
  vars:
    axl_hostname: "{{ lookup('env', 'CUCM_HOST') }}"
    axl_user: "{{ lookup('env', 'CUCM_USER') }}"
    axl_password: "{{ lookup('env', 'CUCM_PASS') }}"
    axl_version: "12.5"
  tasks:
    - name: Fetch CUCM version
      cisco.ucm.axl:
        hostname: "{{ axl_hostname }}"
        username: "{{ axl_user }}"
        password: "{{ axl_password }}"
        verify: false
        version: "{{ axl_version }}"
        operation: "getCCMVersion"
      register: version_response

    - name: Print version
      debug:
        var: version_response.response.componentVersion.version