# hosts.yaml
all:
  hosts:
    cucm_pub:
      ansible_host: 10.29.193.205
      axl_hostname: 10.29.193.205
      axl_user: "administrator"
      axl_password: "C1sc0123!"
      axl_version: "15.0"
      axl_verify: false